name: Deploy via Shared CD Workflow

permissions:
  id-token: write
  contents: read
  
on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      stack-name:
        description: "Name of the CloudFormation stack"
        required: true
        default: sweater-discount-app
      s3-bucket:
        description: "S3 bucket for SAM packaging"
        required: true
        default: aws-sam-cli-managed-default-samclisourcebucket-9oqfaddn9oiy
      region:
        description: "AWS region"
        required: false
        default: eu-west-2
      parameters:
        description: "Additional --parameter-overrides (optional)"
        required: false
        default: |
          --parameter-overrides \
          EmailSecretBucket="crypto-indicator-alert" \
          EmailSecretJsonKey="outlook-email-secret.json" \
          SNSEmailParameter="superbrandonlee@hotmail.com"

jobs:
  trigger-shared-deploy:
    uses: blee1077/github-workflows/.github/workflows/trigger-deploy-aws-sam.yaml@main
    with:
      stack-name: ${{ inputs.stack-name }}
      s3-bucket: ${{ inputs.s3-bucket }}
      region: ${{ inputs.region }}
      parameters: ${{ inputs.parameters }}
