name: Deploy via Shared CD Workflow

permissions:
  id-token: write
  contents: read
  
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  trigger-shared-deploy:
    uses: blee1077/github-workflows/.github/workflows/trigger-deploy-aws-sam.yaml@main
    with:
      stack-name: sweater-discount-app
      s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-9oqfaddn9oiy
      region: eu-west-2
      parameters: --parameter-overrides \
        EmailSecretBucket=crypto-indicator-alert \
        EmailSecretJsonKey=outlook-email-secret.json \
        SNSEmailParameter=superbrandonlee@hotmail.com \
        ScheduleEnabled=false
    secrets: inherit